[strings]
;название игры для отображения в Windows
GameName=SW
;Строка выдаваемая при отсутствии CD с игрой
NotCD=请将游戏光盘插入光驱
;BuyCommand=register.exe
BuyCommand=http://www.buy.com/
FinalLink=http://www.sigma-team.net
;string for incorrect DirectX version
DXError=DirectX 8 or above not found. Please upgrade your DirectX Version at http://www.microsoft.com/directx
;command for exec for incorrect DirectX version
DXErrorCommand=http://www.microsoft.com/directx

[menu]
Lvl=关卡
LvlDiff=难度等级:
Hard=困难
Normal=普通
Easy=简单
Addon2=战役3
Addon=战役2
Help=按 F1 查看帮助
Windowed=窗口模式
Fullscreen=全屏
Play=新游戏
Info=游戏信息
Options=选项
FameHall=最高分
Credits=制作人员
Exit=退出
SelMode=请选择游戏模式
SelPlayer=请选择存档
Campaign=战役
PlayerName=玩家名称:
Empty=空
Cont=继续游戏
Survive=生存模式
Name=名称:
EntName=请输入名称
MainMenu=主菜单
MusicVolume=音乐音量
SoundVolume=音效音量
GraphDetail=画面细节
Scores=成绩:
Scor=得分:
GameOver=任务失败
Money=金钱:
PlayTime=本关时间结束
High=高
Medium=中
Low=低 
SoundVol=音效音量
MusicVol=音乐音量
Back=返回
Continue=继续
SpaceBar=按空格键继续
AnyKeyForRebirth=按空格键重生
Gameover=任务失败
DefaultName=存档1
SaveName=存档
MissionComplete=任务完成
Eqp=装备:
Weapon=武器:
Health=生命:
Str=力量:
Speed=速度:
Acc=精度:
Time=关卡时间:
LevelComplite=本关完成!
Kills=击杀:
FoundMoney=获得金钱:
FoundSecret=发现秘密:
ContinuePress=按任意键继续!
othergames1=其他游戏
othergames2=来自 SIGMA TEAM:
Screentype=屏幕模式:
Greenblood=- 绿色血
Version=版权所有 2002-2004 sigma team.                    完全版 1.22
;параметры игрока
MaxHP=生命:
MaxSTR=力量:
MaxSPD=速度:
MaxACC=精度:

[items]
FindSecret=发现秘密
;бронежилет 
Item204=装备:绿色护甲
Item205=装备:黄色护甲
Item206=装备:红色护甲
Item207=无敌
Item210=+20 生命
Item211=+50 生命
Item212=+100 超级治疗
Item230=装备:救援包
Item236=装备:战斗无人机
Item234=冻结敌人
Item235=+1 生命
Item236=炸弹
Item260=武器:外星枪
Item262=武器:霰弹枪
Item263=武器:榴弹发射器
Item264=武器:转管机枪
Item265=武器:火箭发射器
Item266=武器:冷冻步枪
Item267=武器:等离子步枪
Item268=武器:火焰喷射器
Item269=武器:熔岩转管机枪
Item301=装备:炸药
Item302=弹药:霰弹枪
Item303=弹药:榴弹发射器
Item304=弹药:转管机枪       
Item305=弹药:火箭发射器 
Item306=弹药:冷冻步枪
Item307=弹药:等离子步枪
Item308=弹药:火焰喷射器  
Item309=弹药:熔岩转管机枪  
Item241=+50 金钱
Item242=装备:调整治疗植入体
Item243=装备:调整力量植入体
Item244=装备:调整速度植入体
Item245=装备:调整精度植入体
